[package]
name = "upload"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = ["DomTokenList", "HtmlElement"] }
yew = { version = "0.21.0", features = ["csr"] }
